version: "3.8"

services:
  # Service de développement
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    profiles:
      - dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Service de production
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    profiles:
      - prod
    ports:
      - "80:80"
